package pe.com.maestro.commercial.models;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;

import pe.com.maestro.commercial.db.Contract;
import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.util.CursorUtils;

public class Alert extends EntityBase<Alert> {

	private long id;
	private long clientId;	
	private String message;	
	private boolean isFinancialProductAlert;

	@Override
	public long getID() {		
		return id;
	}

	@Override
	public void setID(long id) {
		this.id = id;
	}

	@Override
	public boolean isAutoGeneratedId() {		
		return false;
	}

	@Override
	public String getTableName() {		
		return Contract.Alert.TABLE_NAME;
	}

	@Override
	public void setValues() {		
		setValue(Contract.Alert._ID, getID());
		setValue(Contract.Alert.COLUMN_CLIENT_ID, getClientId());
		setValue(Contract.Alert.COLUMN_CONTENT, getMessage());
	}
	
	@Override
	public Object getValue(String key) {		
		return null;
	}

	@Override
	public String getDescription() {		
		return this.message;
	}

	public long getClientId() {
		return clientId;
	}

	public void setClientId(long clientId) {
		this.clientId = clientId;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}
	
	public boolean isFinancialProductAlert(){
		return isFinancialProductAlert;
	}
	
	public void setIsFinancialProductAlert(boolean isFinancialProductAlert){
		this.isFinancialProductAlert = isFinancialProductAlert;
	}
	
	public static void deleteClientAlerts(DataBase db, long clientId){
		db.delete(Contract.Alert.TABLE_NAME, Contract.Alert.COLUMN_CLIENT_ID + " = ?", clientId );
	}
	
	public static List<Alert> getAlerts(DataBase db, long clientId){
		List<Alert> alerts = new ArrayList<Alert>();
		
		Cursor c = db.query(Contract.Alert.TABLE_NAME, new String[] {
				Contract.Alert._ID,
				Contract.Alert.COLUMN_CONTENT
		}, Contract.Alert.COLUMN_CLIENT_ID + " = ?", String.valueOf(clientId));
		
		if(c.moveToFirst())
		{
			do{
				Alert a = new Alert();
				a.setID(CursorUtils.getLong(c, Contract.Alert._ID));
				a.setMessage(CursorUtils.getString(c,Contract.Alert.FIELD_CONTENT));
				a.setClientId(clientId);
				
				alerts.add(a);
			}while(c.moveToNext());
		}
		
		return alerts;		
	}

	
}
