package pe.com.maestro.commercial.models;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;

import pe.com.maestro.commercial.db.Contract;
import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.util.CursorUtils;

public class FinancialProduct extends EntityBase<FinancialProduct>{

	private long id;
	private String name;


	@Override
	public long getID() {		
		return id;
	}

	@Override
	public void setID(long id) {
		this.id = id;
	}

	@Override
	public boolean isAutoGeneratedId() {		
		return false;
	}

	@Override
	public String getTableName() {		
		return Contract.FinancialProduct.TABLE_NAME;
	}

	@Override
	public void setValues() {
		setValue(Contract.FinancialProduct._ID, id);
		setValue(Contract.FinancialProduct.COLUMN_NAME, name);
	}

	@Override
	public Object getValue(String key) {		
		return null;
	}
	
	@Override
	public String getDescription() {		
		return this.name;
	}
	
	public String getName(){
		return name;
	}
	
	public void setName(String name){
		this.name = name;
	}
	
	public String getFileName(){
		return "P" + String.valueOf(this.id);
	}

	public static List<FinancialProduct> getFinancialProducts(DataBase db){
		List<FinancialProduct> list = new ArrayList<FinancialProduct>();
		
		Cursor c = db.query(Contract.FinancialProduct.TABLE_NAME, new String[]{
			Contract.FinancialProduct._ID,
			Contract.FinancialProduct.COLUMN_NAME
		},null,null,null,null, Contract.FinancialProduct.COLUMN_NAME);
		
		if(c.moveToFirst()){
			do{
				FinancialProduct p = new FinancialProduct();
				p.setID(CursorUtils.getLong(c,Contract.FinancialProduct._ID));
				p.setName( CursorUtils.getString(c,Contract.FinancialProduct.COLUMN_NAME) );
				
				list.add(p);
			}while(c.moveToNext());
		}
		
		return list;
	}
	
}
