package pe.com.maestro.commercial.models;


import android.database.Cursor;

import pe.com.maestro.commercial.R;
import pe.com.maestro.commercial.db.Contract;
import rp3.data.SimpleDictionary;
import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.runtime.Session;
import rp3.util.CursorUtils;

public class GeoDivision extends EntityBase<GeoDivision> {

	private int id;
	private int departmentId;
	private int provinceId;
	private int districtId;
	private String departmentName;
	private String provinceName;
	private String districtName;
	
	@Override
	public long getID() {		
		return id;
	}

	@Override
	public void setID(long id) {
		this.id = (int)id;
	}

	@Override
	public boolean isAutoGeneratedId() {		
		return false;
	}

	@Override
	public String getTableName() {	
		return Contract.GeoDivision.TABLE_NAME;
	}

	@Override
	public void setValues() {
		
		setValue(Contract.GeoDivision._ID, this.getID());		
		setValue(Contract.GeoDivision.COLUMN_DEPARTMENT_ID, this.getDepartmentId());
		setValue(Contract.GeoDivision.COLUMN_DEPARTMENT_NAME, this.getDepartmentName());
		setValue(Contract.GeoDivision.COLUMN_DISTRICT_ID, this.getDistrictId());
		setValue(Contract.GeoDivision.COLUMN_DISTRICT_NAME, this.getDistrictName());
		setValue(Contract.GeoDivision.COLUMN_PROVINCE_ID, this.getProvinceId());
		setValue(Contract.GeoDivision.COLUMN_PROVINCE_NAME, this.getProvinceName());
	}
	
	@Override
	public Object getValue(String key) {		
		return null;
	}

	@Override
	public String getDescription() {		
		return this.getProvinceName();
	}	

	public int getDepartmentId() {
		return departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	public int getProvinceId() {
		return provinceId;
	}

	public void setProvinceId(int provinceId) {
		this.provinceId = provinceId;
	}

	public int getDistrictId() {
		return districtId;
	}

	public void setDistrictId(int districtId) {
		this.districtId = districtId;
	}

	public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getProvinceName() {
		return provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	public String getDistrictName() {
		return districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}
	
	public static long getIDFromParts(DataBase db, int departmentId, int provinceId, int districtId){
		Cursor c = db.query(Contract.GeoDivision.TABLE_NAME, new String[] {
				Contract.GeoDivision._ID}, 
				Contract.GeoDivision.WHERE_PARTS,
				new String[] {
					String.valueOf(departmentId),
					String.valueOf(provinceId),
					String.valueOf(districtId)
				});
		
		if(c.moveToFirst())
			return CursorUtils.getLong(c);
		
		return 0;
	}
	
	public static GeoDivision getGeoDivision(DataBase db, long id){
		Cursor c = db.query(Contract.GeoDivision.TABLE_NAME, new String[] {
				Contract.GeoDivision._ID,
				Contract.GeoDivision.COLUMN_DISTRICT_ID,
				Contract.GeoDivision.COLUMN_DISTRICT_NAME,
				Contract.GeoDivision.COLUMN_PROVINCE_ID,
				Contract.GeoDivision.COLUMN_PROVINCE_NAME,
				Contract.GeoDivision.COLUMN_DEPARTMENT_ID,
				Contract.GeoDivision.COLUMN_DEPARTMENT_NAME			
			}, Contract.GeoDivision._ID +" = ?", String.valueOf(id));
		
		GeoDivision geo = null;
		
		if(c.moveToNext()){
			geo = new GeoDivision();
			geo.setID(id);
			geo.setDepartmentId( CursorUtils.getInt(c, Contract.GeoDivision.FIELD_DEPARTMENT_ID) );
			geo.setProvinceId( CursorUtils.getInt(c, Contract.GeoDivision.FIELD_PROVINCE_ID) );
			geo.setDistrictId( CursorUtils.getInt(c, Contract.GeoDivision.FIELD_DISTRICT_ID) );
			
			geo.setDepartmentName( CursorUtils.getString(c, Contract.GeoDivision.FIELD_DEPARTMENT_NAME) );
			geo.setProvinceName( CursorUtils.getString(c, Contract.GeoDivision.FIELD_PROVINCE_NAME) );
			geo.setDistrictName( CursorUtils.getString(c, Contract.GeoDivision.FIELD_DISTRICT_NAME) );
		}
		
		return geo;
	}
	
	public static SimpleDictionary getDepartments(DataBase db){
		
		SimpleDictionary data = new SimpleDictionary();
		
		Cursor c = db.query(true, Contract.GeoDivision.TABLE_NAME, new String[] {
			Contract.GeoDivision.COLUMN_DEPARTMENT_ID,
			Contract.GeoDivision.COLUMN_DEPARTMENT_NAME			
		}, null, null, null, null, Contract.GeoDivision.COLUMN_DEPARTMENT_NAME);
		
		
		if(c.moveToFirst()){
			data.set((long) 0, Session.getContext().getText(R.string.hint_default_select_element).toString());
			do{				
				data.set(CursorUtils.getLong(c, Contract.GeoDivision.COLUMN_DEPARTMENT_ID),
						CursorUtils.getString(c, Contract.GeoDivision.COLUMN_DEPARTMENT_NAME));
				
			}while(c.moveToNext());
		}
				
		return data;
	}

	public static SimpleDictionary getProvinces(DataBase db, long departmentId){
		
		SimpleDictionary data = new SimpleDictionary();
		
		Cursor c = db.query(true, Contract.GeoDivision.TABLE_NAME, new String[] {
			Contract.GeoDivision.COLUMN_PROVINCE_ID,
			Contract.GeoDivision.COLUMN_PROVINCE_NAME
		},Contract.GeoDivision.COLUMN_DEPARTMENT_ID + " = ?", new String[] { String.valueOf(departmentId) },
			null, null, Contract.GeoDivision.COLUMN_PROVINCE_NAME);
		
		
		if(c.moveToFirst()){
			data.set((long) 0, Session.getContext().getText(R.string.hint_default_select_element).toString());
			do{
				data.set(CursorUtils.getLong(c, Contract.GeoDivision.COLUMN_PROVINCE_ID), 
						CursorUtils.getString(c, Contract.GeoDivision.COLUMN_PROVINCE_NAME));
				
			}while(c.moveToNext());
		}
				
		return data;
	}
		
	
	public static SimpleDictionary getDistrict(DataBase db, long provinceId){
		
		SimpleDictionary data = new SimpleDictionary();
		
		Cursor c = db.query(true, Contract.GeoDivision.TABLE_NAME, new String[] {
			Contract.GeoDivision.COLUMN_DISTRICT_ID,
			Contract.GeoDivision.COLUMN_DISTRICT_NAME			
		},Contract.GeoDivision.COLUMN_PROVINCE_ID + " = ?", new String[] { String.valueOf(provinceId) },
			null, null, Contract.GeoDivision.COLUMN_DISTRICT_NAME);
				
		if(c.moveToFirst()){
			do{
				data.set((long) 0, Session.getContext().getText(R.string.hint_default_select_element).toString());
				data.set(CursorUtils.getLong(c, Contract.GeoDivision.COLUMN_DISTRICT_ID),
						CursorUtils.getString(c, Contract.GeoDivision.COLUMN_DISTRICT_NAME));
				
			}while(c.moveToNext());
		}
				
		return data;
	}
}
