package pe.com.maestro.commercial.models;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;
import pe.com.maestro.commercial.db.Contract;
import rp3.db.sqlite.DataBase;
import rp3.util.CursorUtils;

public class GuideSection extends rp3.data.entity.EntityBase<GuideSection> {

	private String name;
	private long id;
	private List<GuideElement> guideHeaderElements;
	
	@Override
	public long getID() {		
		return id;
	}

	@Override
	public void setID(long id) {
		this.id = id;
	}

	@Override
	public boolean isAutoGeneratedId() {		
		return false;
	}

	@Override
	public String getTableName() {		
		return Contract.GuideSection.TABLE_NAME;
	}

	@Override
	public void setValues() {
		setValue(Contract.GuideSection._ID, id);
		setValue(Contract.GuideSection.COLUMN_NAME, name);
	}

	@Override
	public Object getValue(String key) {	
		return null;
	}

	@Override
	public String getDescription() {		
		return this.name;
	}

	public void setName(String name){
		this.name = name;
	}
	
	public String getName(){
		return this.name;
	}
	
	public String getFileName(){
		return "E" + String.valueOf(this.id);
	}
	
	public List<GuideElement> getHeaderGuideElements(){
		if(guideHeaderElements==null) guideHeaderElements = new ArrayList<GuideElement>();
		return guideHeaderElements;
	}
	
	public static List<GuideSection> getGuideSections(DataBase db, boolean includeHeadersChilds){
		List<GuideSection> sections = new ArrayList<GuideSection>();
		
		Cursor c = db.query(Contract.GuideSection.TABLE_NAME, 
				new String[] {
						Contract.GuideSection._ID,
						Contract.GuideSection.COLUMN_NAME						
					});
		
		List<GuideElement> childs = null;
		if(includeHeadersChilds){
			childs = GuideElement.getHeadersGuideElements(db);
		}
		
		if(c.moveToFirst()){
			do{
				GuideSection section = new GuideSection();
				section = new GuideSection();
				section.setName( CursorUtils.getString(c, Contract.GuideSection.FIELD_NAME) );				
				section.setID(CursorUtils.getLong(c, Contract.GuideSection._ID));
				
				sections.add(section);								
				
				if(includeHeadersChilds){
					for(GuideElement element: childs){
						if(element.getGuideSectionId() == section.getID()){
							section.getHeaderGuideElements().add(element);
						}
					}
					
					childs.removeAll(section.getHeaderGuideElements());
				}
				
			}while(c.moveToNext());
		}
		
		return sections;
	}
}
