package pe.com.maestro.commercial.models;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;
import pe.com.maestro.commercial.db.Contract;
import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.util.CursorUtils;

public class StoreSection extends EntityBase<StoreSection> {
	
	private int id;
	private int storeSectionId;
	private String name;

	@Override
	public long getID() {		
		return id;
	}

	@Override
	public void setID(long id) {
		this.id = (int)id;
	}

	@Override
	public boolean isAutoGeneratedId() {
		return true;
	}

	@Override
	public String getTableName() {		
		return Contract.StoreSection.TABLE_NAME;
	}

	@Override
	public void setValues() {	
		if(getAction() != ACTION_INSERT)
			setValue(Contract.StoreSection._ID, this.getID());
		
		setValue(Contract.StoreSection.COLUMN_STORESECTION_ID, this.getStoreSectionId());
		setValue(Contract.StoreSection.COLUMN_NAME, this.getName());
	}
	
	@Override
	public Object getValue(String key) {		
		return null;
	}

	@Override
	public String getDescription() {		
		return this.getName();
	}

	public int getStoreSectionId() {
		return storeSectionId;
	}

	public void setStoreSectionId(int storeSectionId) {
		this.storeSectionId = storeSectionId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public static List<StoreSection> getStoreSections(DataBase db){
		List<StoreSection> list = new ArrayList<StoreSection>();
		Cursor c = getStoreSectionCursor(db);
		while(c.moveToNext()){
			StoreSection s = new StoreSection();
			s.setID( CursorUtils.getLong(c, Contract.StoreSection._ID) );
			s.setName( CursorUtils.getString(c, Contract.StoreSection.COLUMN_NAME) );
			s.setStoreSectionId( CursorUtils.getInt(c, Contract.StoreSection.COLUMN_STORESECTION_ID) );
			list.add(s);
		}		
		return list;
	}
	
	public static Cursor getStoreSectionCursor(DataBase db){
		return db.query(Contract.StoreSection.TABLE_NAME, new String[] {
			Contract.StoreSection._ID,
			Contract.StoreSection.COLUMN_STORESECTION_ID,
			Contract.StoreSection.COLUMN_NAME
		}, null, null, null,null, Contract.StoreSection.COLUMN_NAME);
	}
	
}
