package pe.com.maestro.commercial.models;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;
import pe.com.maestro.commercial.db.Contract;
import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.util.CursorUtils;

public class Store extends EntityBase<Store> {

	private int id;
	private String storeId;
	private String name;

	@Override
	public long getID() {
		return id;
	}

	@Override
	public void setID(long id) {
		id = (int) id;
	}

	@Override
	public boolean isAutoGeneratedId() {
		return true;
	}

	@Override
	public String getTableName() {
		return Contract.Store.TABLE_NAME;
	}

	@Override
	public void setValues() {
		if (this.getAction() != ACTION_INSERT)
			setValue(Contract.Store._ID, getID());
		setValue(Contract.Store.COLUMN_STORE_ID, getStoreId());
		setValue(Contract.Store.COLUMN_NAME, getName());
	}

	@Override
	public Object getValue(String key) {
		return null;
	}

	@Override
	public String getDescription() {
		return this.name;
	}

	public String getStoreId() {
		return storeId;
	}

	public void setStoreId(String string) {
		this.storeId = string;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public static Store getStore(DataBase db, String code) {
		Cursor c = db.query(Contract.Store.TABLE_NAME, new String[] {
				Contract.Store._ID, Contract.Store.COLUMN_STORE_ID,
				Contract.Store.COLUMN_NAME }, Contract.Store.COLUMN_STORE_ID
				+ " = ?", code);		

		Store s = null;
		if (c.moveToFirst()) {
			s = new Store();
			s.setID(CursorUtils.getLong(c, Contract.Store._ID));
			s.setName(CursorUtils.getString(c, Contract.Store.FIELD_NAME));
			s.setStoreId(CursorUtils.getString(c, Contract.Store.FIELD_STOREID));
		}
		return s;
	}

	public static List<Store> getStores(DataBase db) {
		List<Store> stores = new ArrayList<Store>();

		Cursor c = getStoresCursor(db);
		if (c.moveToFirst()) {
			do {
				Store s = new Store();
				s.setID(CursorUtils.getLong(c, Contract.Store._ID));
				s.setName(CursorUtils.getString(c, Contract.Store.FIELD_NAME));
				s.setStoreId(CursorUtils.getString(c,
						Contract.Store.FIELD_STOREID));

				stores.add(s);
			} while (c.moveToNext());
		}
		return stores;
	}

	public static Cursor getStoresCursor(DataBase db) {
		Cursor c = db.query(Contract.Store.TABLE_NAME, new String[] {
				Contract.Store._ID, Contract.Store.COLUMN_STORE_ID,
				Contract.Store.COLUMN_NAME,
				}, null,null, null,null, Contract.Store.COLUMN_NAME);
		return c;
	}
}
